[package]
authors = ["Cole Lawrence <cole@colelawrence.com>"]
edition = "2018"
name = "layered-nlp"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# rust_decimal = {version = "1.10.3", features = ["std"]}
# type-map = "0.5.0"

[dev-dependencies]
insta = "1.6.3"
