[package]
name = "layered-part-of-speech"
version = "0.1.0"
authors = ["leudz <dylan.ancel@gmail.com>"]
edition = "2018"

[dependencies]
layered-nlp = { path = ".." }
wiktionary-part-of-speech-extract = "0.1.0"
