[package]
name = "layered-part-of-speech"
version = "0.1.0"
authors = ["leudz <dylan.ancel@gmail.com>"]
edition = "2018"

[build-dependencies]
fst = "0.4.5"

[dependencies]
fst = "0.4.5"
layered-nlp = { path = ".." }
insta = "1.7.0"
