[package]
name = "layered-clauses"
version = "0.1.0"
authors = ["leudz <dylan.ancel@gmail.com>"]
edition = "2018"

[dependencies]
layered-nlp = { path = ".." }

[dev-dependencies]
insta = "1.7.1"
layered-part-of-speech = { path = "../layered-part-of-speech" }
